# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Hallo_class(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Photo/IMG-20251105-1WA0016.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #F8F9FA;\n"
"    color: #2C3E50;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #F8F9FA;\n"
"    color: #2C3E50;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 12px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 460, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 440, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 10, 291, 41))
        self.label.setStyleSheet("/* Обычная метка */\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    color: #2C3E50;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    font-weight: normal;\n"
"    padding: 2px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Важная метка */\n"
"QLabel[important=\"true\"] {\n"
"    font-weight: bold;\n"
"    color: #2C3E50;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Заголовок */\n"
"QLabel[title=\"true\"] {\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    color: #1A5276;\n"
"    padding: 5px;\n"
"}")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 380, 110, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #E74C3C;\n"
"    color: #FFFFFF;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    padding: 8px 15px;\n"
"    min-width: 80px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CB4335;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A93226;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F5B7B1;\n"
"    color: #7F8C8D;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 50, 641, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(190, 120, 271, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 0, 5, 10)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setStyleSheet("QPushButton[gradient=\"true\"] {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #E74C3C, stop:1 #CB4335);\n"
"    color: #FFFFFF;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #A93226;\n"
"    border-radius: 3px;\n"
"    padding: 8px 15px;\n"
"}\n"
"\n"
"QPushButton[gradient=\"true\"]:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #CB4335, stop:1 #A93226);\n"
"}\n"
"\n"
"QPushButton[gradient=\"true\"]:pressed {\n"
"    background-color: #A93226;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "@Scorpionsnik"))
        self.label_2.setText(_translate("MainWindow", "Mathgames  2.1.1"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">Добро пожаловат в Mathgames!</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "ВЫХОД"))
        self.pushButton.setText(_translate("MainWindow", "Начать работу"))
