# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resh_prim.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow_1(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(1920, 1080)
        mainwindow.setStyleSheet("QMainWindow {\n"
"    background: qconicalgradient(cx: 0.5, cy: 0.5, angle: 45,\n"
"                                 stop: 0 #FFD699, stop: 0.2 #FFCC80,\n"
"                                 stop: 0.4 #FFC266, stop: 0.6 #FFB84D,\n"
"                                 stop: 0.8 #FFAD33, stop: 1 #FFA31A);\n"
"    border: 6px double #FF9800;\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"QWidget#centralwidget {\n"
"    background: rgba(255, 243, 224, 0.85);\n"
"    border: 5px solid #FFB347;\n"
"    border-radius: 25px;\n"
"    margin: 15px;\n"
"}\n"
"\n"
"/* Многослойная граница для окна */\n"
"QMainWindow::separator {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 #FF9800, stop:0.3 #FFB347, \n"
"                                stop:0.7 #FFCC33, stop:1 #FF9800);\n"
"    width: 3px;\n"
"    height: 3px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 120, 1881, 911))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(450, 0, -1, -1)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #7F4F24;  /* Тот же теплый коричневый, что и у кнопки */\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 40px;\n"
"    font-weight: normal;\n"
"    background: transparent;  /* Прозрачный фон */\n"
"    border: none;  /* Без границ */\n"
"    padding: 5px 0px;\n"
"}\n"
"\n"
"QLabel[important=\"true\"] {\n"
"    font-weight: bold;\n"
"    color: #E68900;  /* Более яркий цвет для важных надписей */\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #CC9966;  /* Приглушенный цвет для неактивных надписей */\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(250)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(223, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #7F4F24;  /* Тот же теплый коричневый, что и у кнопки */\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 40px;\n"
"    font-weight: normal;\n"
"    background: transparent;  /* Прозрачный фон */\n"
"    border: none;  /* Без границ */\n"
"    padding: 5px 0px;\n"
"}\n"
"\n"
"QLabel[important=\"true\"] {\n"
"    font-weight: bold;\n"
"    color: #E68900;  /* Более яркий цвет для важных надписей */\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #CC9966;  /* Приглушенный цвет для неактивных надписей */\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(800, 66))
        self.lineEdit.setMaximumSize(QtCore.QSize(800, 70))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #FFF9F0;  /* Очень светлый персиковый фон */\n"
"    border: 3px solid #FFB347;  /* Чуть толще граница для баланса */\n"
"    border-radius: 15px;        /* Увеличим скругление */\n"
"    color: #7F4F24;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 24px;           /* Было 16px, стало 24px (в 1.5 раза больше) */\n"
"    font-weight: normal;\n"
"    padding: 15px 20px;        /* Увеличим отступы */\n"
"    selection-background-color: #FFCC33;  /* Цвет выделения текста */\n"
"    min-height: 30px;          /* Добавим минимальную высоту */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 3px solid #FF9800;\n"
"    background-color: #FFF5E6;  /* Чуть темнее при фокусе */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #FFF5E6;\n"
"    border: 3px solid #FF9800;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #CC9966;  /* Цвет текста-подсказки */\n"
"    font-style: italic;\n"
"    font-size: 20px;  /* Увеличим размер placeholder тоже */\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(75, 50, 0, 50)
        self.verticalLayout_3.setSpacing(30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #e74c3c;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #e74c3c;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FFB347, stop: 1 #FFCC33);\n"
"    border: 3px solid #FF9800; /* Немного толще граница для баланса */\n"
"    border-radius: 20px; /* Увеличим скругление */\n"
"    color: #7F4F24;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 42px; /* Было 14px, стало 42px */\n"
"    font-weight: bold;\n"
"    padding: 20px 30px; /* Увеличим отступы */\n"
"    min-height: 80px; /* Минимальная высота для удобства */\n"
"    min-width: 200px; /* Минимальная ширина */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FFCC33, stop: 1 #FFB347);\n"
"    border: 3px solid #E68900;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #E68900, stop: 1 #FF9900);\n"
"    padding: 22px 28px 18px 32px; /* Скорректированный эффект нажатия */\n"
"}")







        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 9, 1901, 211))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #e74c3c;\n"
"    font-size: 50px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}")
        self.label_5.setObjectName("label_5")
        







        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FFB347, stop: 1 #FFCC33);\n"
"    border: 3px solid #FF9800; /* Немного толще граница для баланса */\n"
"    border-radius: 20px; /* Увеличим скругление */\n"
"    color: #7F4F24;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 42px; /* Было 14px, стало 42px */\n"
"    font-weight: bold;\n"
"    padding: 20px 30px; /* Увеличим отступы */\n"
"    min-height: 80px; /* Минимальная высота для удобства */\n"
"    min-width: 200px; /* Минимальная ширина */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FFCC33, stop: 1 #FFB347);\n"
"    border: 3px solid #E68900;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #E68900, stop: 1 #FF9900);\n"
"    padding: 22px 28px 18px 32px; /* Скорректированный эффект нажатия */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(350, -1, -1, 30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(400, 100))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FF6B6B, stop: 1 #FF8E8E);\n"
"    border: 3px solid #FF5252;\n"
"    border-radius: 20px;\n"
"    color: #7C2D2D;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 42px;\n"
"    font-weight: bold;\n"
"    padding: 20px 30px;\n"
"    min-height: 80px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FF8E8E, stop: 1 #FF6B6B);\n"
"    border: 3px solid #E04040;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #E04040, stop: 1 #FF5252);\n"
"    padding: 22px 28px 18px 32px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FFCCCC, stop: 1 #FFDDDD);\n"
"    border: 3px solid #FFAAAA;\n"
"    color: #CC8888;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        mainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "mathgames"))
        self.label.setText(_translate("mainwindow", "TextLabel"))
        self.label_2.setText(_translate("mainwindow", "Твой ответ:"))
        self.label_3.setText(_translate("mainwindow", "<html><head/><body><p align=\"center\">ВЕРНО!</p></body></html>"))
        self.label_4.setText(_translate("mainwindow", "Оценка: 5"))
        self.label_5.setText(_translate("mainwindow", "Оценка: 5"))
        self.pushButton.setText(_translate("mainwindow", "Проверить"))
        self.pushButton_4.setText(_translate("mainwindow", "Следущий пример"))
        self.pushButton_2.setText(_translate("mainwindow", "ВЫХОД"))
