# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sozd_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Sozd_f(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Photo/IMG-20251105-1WA0016.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-3, 60, 651, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-3, 370, 651, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 390, 641, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout.setSpacing(200)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # Кнопка ВЫХОД - ярко-красная
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setStyleSheet("""
            QPushButton {
                border: 3px solid #FF0000;
                border-radius: 10px;
                background-color: qlineargradient(
                    x1: 0, y1: 0, 
                    x2: 0, y2: 1,
                    stop: 0 #FF0000,
                    stop: 0.5 #FF3838, 
                    stop: 1 #FF0000
                );
                color: #FFFFFF;
                font-weight: bold;
                font-size: 14px;
                padding: 10px 20px;
                min-width: 90px;
            }
            QPushButton:hover {
                background-color: qlineargradient(
                    x1: 0, y1: 0, 
                    x2: 0, y2: 1,
                    stop: 0 #FF3838,
                    stop: 0.5 #FF5252,
                    stop: 1 #FF3838
                );
                border: 3px solid #FF6B6B;
                color: #FFFFFF;
            }
            QPushButton:pressed {
                background-color: qlineargradient(
                    x1: 0, y1: 0, 
                    x2: 0, y2: 1,
                    stop: 0 #CC0000,
                    stop: 0.5 #E60000,
                    stop: 1 #CC0000
                );
                border: 3px solid #FF9999;
                color: #FFE6E6;
            }
        """)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        
        # Кнопка ДАЛЕЕ - ярко-зеленая
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setStyleSheet("""
            QPushButton {
                border: 3px solid #00FF00;
                border-radius: 10px;
                background-color: qlineargradient(
                    x1: 0, y1: 0, 
                    x2: 0, y2: 1,
                    stop: 0 #00FF00,
                    stop: 0.5 #32CD32,
                    stop: 1 #00FF00
                );
                color: #000000;
                font-weight: bold;
                font-size: 14px;
                padding: 10px 20px;
                min-width: 90px;
            }
            QPushButton:hover {
                background-color: qlineargradient(
                    x1: 0, y1: 0, 
                    x2: 0, y2: 1,
                    stop: 0 #32CD32,
                    stop: 0.5 #7CFC00,
                    stop: 1 #32CD32
                );
                border: 3px solid #ADFF2F;
                color: #000000;
            }
            QPushButton:pressed {
                background-color: qlineargradient(
                    x1: 0, y1: 0, 
                    x2: 0, y2: 1,
                    stop: 0 #00CC00,
                    stop: 0.5 #00EE00,
                    stop: 1 #00CC00
                );
                border: 3px solid #9ACD32;
                color: #003300;
            }
        """)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 80, 301, 291))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(50, 0, 50, 25)
        self.verticalLayout_4.setSpacing(50)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setStyleSheet("color: red; font-weight: bold; font-size: 14px;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_9.setStyleSheet("font-size: 12px; color: #666666;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        # self.lineEdit_3.setStyleSheet("""
        #     QLineEdit {
        #         border: 2px solid #8B0000;
        #         border-radius: 8px;
        #         background-color: #2C0A0A;
        #         color: #FF6B6B;
        #         font-weight: bold;
        #         font-size: 12px;
        #         padding: 8px 12px;
        #         selection-background-color: #FF4757;
        #     }
        #     QLineEdit:focus {
        #         border: 2px solid #FF4757;
        #         background-color: #2C0A0A;
        #     }
        # """)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 0, 485, 62))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #2C0A0A; font-weight: bold;")
        self.label_3.setObjectName("label_3")
        
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(350, 76, 281, 291))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(50, 0, 50, 25)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_4.setStyleSheet("color: red; font-weight: bold; font-size: 14px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_10.setStyleSheet("font-size: 12px; color: #666666;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_5)
        # self.spinBox_2.setStyleSheet("""
        #     QSpinBox {
        #         border: 2px solid #8B0000;
        #         border-radius: 8px;
        #         background-color: #2C0A0A;
        #         color: #FF6B6B;
        #         font-weight: bold;
        #         font-size: 12px;
        #         padding: 5px 10px;
        #         selection-background-color: #FF4757;
        #     }
        #     QSpinBox:hover {
        #         border: 2px solid #A52A2A;
        #         background-color: #3A0F0F;
        #     }
        #     QSpinBox:focus {
        #         border: 2px solid #FF4757;
        #         background-color: #2C0A0A;
        #     }
        #     QSpinBox::up-button, QSpinBox::down-button {
        #         background-color: #8B0000;
        #         border: none;
        #         border-radius: 4px;
        #         width: 20px;
        #         margin: 2px;
        #     }
        #     QSpinBox::up-button:hover, QSpinBox::down-button:hover {
        #         background-color: #A52A2A;
        #     }
        #     QSpinBox::up-arrow {
        #         border-left: 4px solid transparent;
        #         border-right: 4px solid transparent;
        #         border-bottom: 8px solid #FF9999;
        #     }
        #     QSpinBox::down-arrow {
        #         border-left: 4px solid transparent;
        #         border-right: 4px solid transparent;
        #         border-top: 8px solid #FF9999;
        #     }
        # """)
        self.spinBox_2.setWrapping(True)
        self.spinBox_2.setPrefix("")
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(50)
        self.spinBox_2.setSingleStep(1)
        self.spinBox_2.setProperty("value", 1)
        self.spinBox_2.setDisplayIntegerBase(10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_5.addWidget(self.spinBox_2)
        
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(310, 70, 20, 311))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(25, 280, 300, 20))
        self.label.setStyleSheet("color: red; font-weight: bold;")
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(56, 360, 301, 20))
        self.label_2.setStyleSheet("color: red; font-weight: bold;")
        self.label_2.setObjectName("label_2")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "создание базы данных"))
        self.pushButton_2.setText(_translate("MainWindow", "ВЫХОД"))
        self.pushButton.setText(_translate("MainWindow", "ДАЛЕЕ"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Пароль администратора:</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">(целочисленный)</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Создание нового файла "))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Число учителей:</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">если точно неизвестно,</p><p align=\"center\"> указывай минимальное, </p><p align=\"center\">потом можно еще создать</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Ты не можешь продолжить без пароля администратора!"))
        self.label_2.setText(_translate("MainWindow", "Пароль должен быть числом!"))