# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class start_win(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Photo/IMG-20251105-1WA0016.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #667eea, stop:1 #764ba2);\n"
"}\n"
"\n"
"QWidget#centralWidget {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QFrame {\n"
"    background: rgba(255, 255, 255, 0.95);\n"
"    border-radius: 20px;\n"
"    border: 2px solid rgba(255, 255, 255, 0.3);\n"
"}\n"
"\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel#titleLabel {\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"    color: #2c3e50;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QLabel#studentInfo {\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 20px;\n"
"    color: #34495e;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel#sectionTitle {\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #2980b9;\n"
"    padding: 8px;\n"
"    border-bottom: 2px solid #3498db;\n"
"}\n"
"\n"
"QLabel#gradesText {\n"
"    font-family: \'Consolas\', monospace;\n"
"    font-size: 22px;\n"
"    color: #2c3e50;\n"
"    padding: 10px;\n"
"    background: rgba(236, 240, 241, 0.7);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLabel#statsValue {\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 20px;\n"
"    color: #27ae60;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#statsLabel {\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 18px;\n"
"    color: #7f8c8d;\n"
"}\n"
"\n"
"QLabel#rankValue {\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 28px;\n"
"    color: #e74c3c;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#rankText {\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 18px;\n"
"    color: #34495e;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 14px;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 #2ecc71, stop:1 #27ae60);\n"
"    border-radius: 8px;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 9, 1901, 211))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color : #D00000")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 250, 1901, 300))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 600, 1901, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setStyleSheet("QPushButton { \n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 12px 25px;\n"
"    min-width: 120px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 12px 25px;\n"
"    min-width: 120px;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: red;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    font-family: \'Segoe UI\', Arial;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 12px 25px;\n"
"    min-width: 120px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Добро пожаловать!"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Начать прохождение?</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Предупреждаем: задание на оценку, </p><p align=\"center\">выполняйте его аккуратно, если не хотите сразу приступать, </p><p align=\"center\">можно потренироваться в пробном режиме, </p><p align=\"center\">но если не пройти обычный режим, можно получить &quot;2&quot;</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Начать прохождение"))
        self.pushButton_3.setText(_translate("MainWindow", "Попробовать примеры"))
        self.pushButton.setText(_translate("MainWindow", "НАЗАД"))
