# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ucenik1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class uchen1(object):
    def setupUi(self, StudentMainWindow):
        StudentMainWindow.setObjectName("StudentMainWindow")
        StudentMainWindow.resize(1000, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Photo/IMG-20251105-1WA0016.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StudentMainWindow.setWindowIcon(icon)
        StudentMainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
"                        stop: 0 #667eea, stop: 1 #764ba2);\n"
"}\n"
"\n"
"QWidget#centralwidget {\n"
"   background: transparent;\n"
"}\n"
"\n"
"QLabel {\n"
"   background: transparent;\n"
"   color: white;\n"
"   font-family: 'Segoe UI', Arial, sans-serif;\n"
"}\n"
"\n"
"QLabel#label_title {\n"
"   font-size: 72px;\n"
"   font-weight: bold;\n"
"   color: white;\n"
"   background: rgba(255, 255, 255, 0.1);\n"
"   border-radius: 25px;\n"
"   padding: 40px;\n"
"}\n"
"\n"
"QLabel#label_welcome {\n"
"   font-size: 36px;\n"
"   color: #f0f0f0;\n"
"}\n"
"\n"
"QFrame#frame_main {\n"
"   background: rgba(255, 255, 255, 0.95);\n"
"   border-radius: 30px;\n"
"   border: 3px solid rgba(255, 255, 255, 0.3);\n"
"}\n"
"\n"
"QPushButton {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #667eea, stop: 1 #764ba2);\n"
"   color: white;\n"
"   border: none;\n"
"   border-radius: 20px;\n"
"   padding: 25px 40px;\n"
"   font-size: 28px;\n"
"   font-weight: bold;\n"
"   font-family: 'Segoe UI', Arial, sans-serif;\n"
"   min-width: 300px;\n"
"   min-height: 90px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #5a6fd8, stop: 1 #6a4190);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #4c5bc4, stop: 1 #5c377e);\n"
"   padding: 26px 41px 24px 39px;\n"
"}\n"
"\n"
"QPushButton#pushButton_practice {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #11998e, stop: 1 #38ef7d);\n"
"}\n"
"\n"
"QPushButton#pushButton_practice:hover {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #0f8a7f, stop: 1 #32d46b);\n"
"}\n"
"\n"
"QPushButton#pushButton_practice:pressed {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #0d7b70, stop: 1 #2cc159);\n"
"   padding: 26px 41px 24px 39px;\n"
"}\n"
"\n"
"QPushButton#pushButton_stats {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #ff6b6b, stop: 1 #ffa8a8);\n"
"}\n"
"\n"
"QPushButton#pushButton_stats:hover {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #e55a5a, stop: 1 #ff9696);\n"
"}\n"
"\n"
"QPushButton#pushButton_stats:pressed {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #d14949, stop: 1 #ff8484);\n"
"   padding: 26px 41px 24px 39px;\n"
"}\n"
"\n"
"QPushButton#pushButton_send_grades {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #f093fb, stop: 1 #f5576c);\n"
"}\n"
"\n"
"QPushButton#pushButton_send_grades:hover {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #e084e2, stop: 1 #e4495e);\n"
"}\n"
"\n"
"QPushButton#pushButton_send_grades:pressed {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #d074d2, stop: 1 #d34053);\n"
"   padding: 26px 41px 24px 39px;\n"
"}\n"
"\n"
"QPushButton#pushButton_exit {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #ff9a9e, stop: 1 #fad0c4);\n"
"   color: #333;\n"
"}\n"
"\n"
"QPushButton#pushButton_exit:hover {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #ff8a8e, stop: 1 #f8c0b4);\n"
"}\n"
"\n"
"QPushButton#pushButton_exit:pressed {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                        stop: 0 #ff7a7e, stop: 1 #f6b0a4);\n"
"   padding: 26px 41px 24px 39px;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(StudentMainWindow)
        self.centralwidget.setStyleSheet("background: transparent;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        spacerItem1 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_welcome = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.verticalLayout.addWidget(self.label_welcome)
        spacerItem2 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.pushButton_practice = QtWidgets.QPushButton(self.frame_main)
        self.pushButton_practice.setObjectName("pushButton_practice")
        self.verticalLayout_2.addWidget(self.pushButton_practice)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.pushButton_stats = QtWidgets.QPushButton(self.frame_main)
        self.pushButton_stats.setObjectName("pushButton_stats")
        self.verticalLayout_2.addWidget(self.pushButton_stats)
        spacerItem5 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        
        # Новая кнопка для отправки оценок учителю
        self.pushButton_send_grades = QtWidgets.QPushButton(self.frame_main)
        self.pushButton_send_grades.setObjectName("pushButton_send_grades")
        self.verticalLayout_2.addWidget(self.pushButton_send_grades)
        
        spacerItem6 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.pushButton_exit = QtWidgets.QPushButton(self.frame_main)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.verticalLayout_2.addWidget(self.pushButton_exit)
        spacerItem7 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addWidget(self.frame_main)
        spacerItem8 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        StudentMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StudentMainWindow)
        QtCore.QMetaObject.connectSlotsByName(StudentMainWindow)

    def retranslateUi(self, StudentMainWindow):
        _translate = QtCore.QCoreApplication.translate
        StudentMainWindow.setWindowTitle(_translate("StudentMainWindow", "MathGames - Учебный портал"))
        self.label_title.setText(_translate("StudentMainWindow", "<html><head/><body><p align=\"center\">🎓 MathGames</p><p align=\"center\"><span style=\" font-size:48pt;\">Учебный портал</span></p></body></html>"))
        self.label_welcome.setText(_translate("StudentMainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:32pt;\">Добро пожаловать, ученик!</span></p><p align=\"center\"><span style=\" font-size:28pt;\">Выберите действие:</span></p></body></html>"))
        self.pushButton_practice.setText(_translate("StudentMainWindow", "📚 Начать занятия"))
        self.pushButton_stats.setText(_translate("StudentMainWindow", "📊 Моя статистика"))
        self.pushButton_send_grades.setText(_translate("StudentMainWindow", "📤 Отправить оценки учителю"))
        self.pushButton_exit.setText(_translate("StudentMainWindow", "🚪 Выход"))