# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uch4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Uch4(object):
    def setupUi(self, TeacherViewWindow):
        TeacherViewWindow.setObjectName("TeacherViewWindow")
        TeacherViewWindow.resize(1280, 960)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Photo/IMG-20251105-1WA0016.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TeacherViewWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(TeacherViewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_class = QtWidgets.QLabel(self.centralwidget)
        self.label_class.setObjectName("label_class")
        self.horizontalLayout_2.addWidget(self.label_class)
        self.comboBox_classes = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_classes.setObjectName("comboBox_classes")
        self.horizontalLayout_2.addWidget(self.comboBox_classes)
        self.pushButton_load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_2.addWidget(self.pushButton_load)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_students = QtWidgets.QLabel(self.centralwidget)
        self.label_students.setObjectName("label_students")
        self.verticalLayout_2.addWidget(self.label_students)
        self.listWidget_students = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_students.setObjectName("listWidget_students")
        self.verticalLayout_2.addWidget(self.listWidget_students)
        
        # Управление оценками - обновленная группа
        self.groupBox_grades = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_grades.setObjectName("groupBox_grades")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_grades)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        
        self.label_3 = QtWidgets.QLabel(self.groupBox_grades)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        
        self.label_grade_num = QtWidgets.QLabel(self.groupBox_grades)
        self.label_grade_num.setObjectName("label_grade_num")
        self.horizontalLayout_4.addWidget(self.label_grade_num)
        
        self.spinBox_grade_num = QtWidgets.QSpinBox(self.groupBox_grades)
        self.spinBox_grade_num.setMinimum(1)
        self.spinBox_grade_num.setMaximum(50)
        self.spinBox_grade_num.setProperty("value", 1)
        self.spinBox_grade_num.setObjectName("spinBox_grade_num")
        self.horizontalLayout_4.addWidget(self.spinBox_grade_num)
        
        self.label_grade_value = QtWidgets.QLabel(self.groupBox_grades)
        self.label_grade_value.setObjectName("label_grade_value")
        self.horizontalLayout_4.addWidget(self.label_grade_value)
        
        self.spinBox_grade_value = QtWidgets.QSpinBox(self.groupBox_grades)
        self.spinBox_grade_value.setMinimum(1)
        self.spinBox_grade_value.setMaximum(5)
        self.spinBox_grade_value.setProperty("value", 5)
        self.spinBox_grade_value.setObjectName("spinBox_grade_value")
        self.horizontalLayout_4.addWidget(self.spinBox_grade_value)
        
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        
        self.pushButton_set_grade = QtWidgets.QPushButton(self.groupBox_grades)
        self.pushButton_set_grade.setObjectName("pushButton_set_grade")
        self.horizontalLayout_7.addWidget(self.pushButton_set_grade)
        
        self.pushButton_delete_grade = QtWidgets.QPushButton(self.groupBox_grades)
        self.pushButton_delete_grade.setObjectName("pushButton_delete_grade")
        self.horizontalLayout_7.addWidget(self.pushButton_delete_grade)
        
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        
        self.verticalLayout_2.addWidget(self.groupBox_grades)
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        
        # РАЗДЕЛЕНИЕ НАСТРОЕК НА 2 КОЛОНКИ
        self.horizontalLayout_settings = QtWidgets.QHBoxLayout()
        self.horizontalLayout_settings.setObjectName("horizontalLayout_settings")
        
        # ЛЕВАЯ КОЛОНКА НАСТРОЕК
        self.verticalLayout_left = QtWidgets.QVBoxLayout()
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        
        # НОВАЯ ГРУППА: Число действий
        self.groupBox_actions = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_actions.setObjectName("groupBox_actions")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_actions)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        
        self.label_actions = QtWidgets.QLabel(self.groupBox_actions)
        self.label_actions.setObjectName("label_actions")
        self.horizontalLayout_8.addWidget(self.label_actions)
        
        self.spinBox_actions = QtWidgets.QSpinBox(self.groupBox_actions)
        self.spinBox_actions.setMinimum(1)
        self.spinBox_actions.setMaximum(10)
        self.spinBox_actions.setProperty("value", 1)
        self.spinBox_actions.setObjectName("spinBox_actions")
        self.horizontalLayout_8.addWidget(self.spinBox_actions)
        
        self.verticalLayout_left.addWidget(self.groupBox_actions)

        # НОВАЯ ГРУППА: Число переменных
        self.groupBox_variables = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_variables.setObjectName("groupBox_variables")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_variables)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        
        self.label_variables = QtWidgets.QLabel(self.groupBox_variables)
        self.label_variables.setObjectName("label_variables")
        self.horizontalLayout_9.addWidget(self.label_variables)
        
        self.spinBox_variables = QtWidgets.QSpinBox(self.groupBox_variables)
        self.spinBox_variables.setMinimum(0)
        self.spinBox_variables.setMaximum(3)
        self.spinBox_variables.setProperty("value", 0)
        self.spinBox_variables.setObjectName("spinBox_variables")
        self.horizontalLayout_9.addWidget(self.spinBox_variables)
        
        self.verticalLayout_left.addWidget(self.groupBox_variables)
        
        # НОВАЯ ГРУППА: Количество примеров
        self.groupBox_examples_count = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_examples_count.setObjectName("groupBox_examples_count")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_examples_count)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        
        self.label_examples_count = QtWidgets.QLabel(self.groupBox_examples_count)
        self.label_examples_count.setObjectName("label_examples_count")
        self.horizontalLayout_10.addWidget(self.label_examples_count)
        
        self.spinBox_examples_count = QtWidgets.QSpinBox(self.groupBox_examples_count)
        self.spinBox_examples_count.setMinimum(1)
        self.spinBox_examples_count.setMaximum(100)
        self.spinBox_examples_count.setProperty("value", 10)
        self.spinBox_examples_count.setObjectName("spinBox_examples_count")
        self.horizontalLayout_10.addWidget(self.spinBox_examples_count)
        
        self.verticalLayout_left.addWidget(self.groupBox_examples_count)
        
        # НОВАЯ ГРУППА: Принцип оценки
        self.groupBox_grading_system = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_grading_system.setObjectName("groupBox_grading_system")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_grading_system)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        
        self.radioButton_standard = QtWidgets.QRadioButton(self.groupBox_grading_system)
        self.radioButton_standard.setObjectName("radioButton_standard")
        self.radioButton_standard.setChecked(True)
        self.verticalLayout_7.addWidget(self.radioButton_standard)
        
        self.radioButton_custom = QtWidgets.QRadioButton(self.groupBox_grading_system)
        self.radioButton_custom.setObjectName("radioButton_custom")
        self.verticalLayout_7.addWidget(self.radioButton_custom)
        
        # СЕТКА ДЛЯ ВВОДА КРИТЕРИЕВ ДЛЯ КАЖДОЙ ОЦЕНКИ
        self.gridLayout_grading = QtWidgets.QGridLayout()
        self.gridLayout_grading.setObjectName("gridLayout_grading")
        
        self.label_for_5 = QtWidgets.QLabel(self.groupBox_grading_system)
        self.label_for_5.setObjectName("label_for_5")
        self.gridLayout_grading.addWidget(self.label_for_5, 0, 0, 1, 1)
        
        self.spinBox_for_5 = QtWidgets.QSpinBox(self.groupBox_grading_system)
        self.spinBox_for_5.setMinimum(1)
        self.spinBox_for_5.setMaximum(100)
        self.spinBox_for_5.setProperty("value", 8)
        self.spinBox_for_5.setObjectName("spinBox_for_5")
        self.gridLayout_grading.addWidget(self.spinBox_for_5, 0, 1, 1, 1)
        
        self.label_for_4 = QtWidgets.QLabel(self.groupBox_grading_system)
        self.label_for_4.setObjectName("label_for_4")
        self.gridLayout_grading.addWidget(self.label_for_4, 1, 0, 1, 1)
        
        self.spinBox_for_4 = QtWidgets.QSpinBox(self.groupBox_grading_system)
        self.spinBox_for_4.setMinimum(1)
        self.spinBox_for_4.setMaximum(100)
        self.spinBox_for_4.setProperty("value", 6)
        self.spinBox_for_4.setObjectName("spinBox_for_4")
        self.gridLayout_grading.addWidget(self.spinBox_for_4, 1, 1, 1, 1)
        
        self.label_for_3 = QtWidgets.QLabel(self.groupBox_grading_system)
        self.label_for_3.setObjectName("label_for_3")
        self.gridLayout_grading.addWidget(self.label_for_3, 2, 0, 1, 1)
        
        self.spinBox_for_3 = QtWidgets.QSpinBox(self.groupBox_grading_system)
        self.spinBox_for_3.setMinimum(1)
        self.spinBox_for_3.setMaximum(100)
        self.spinBox_for_3.setProperty("value", 4)
        self.spinBox_for_3.setObjectName("spinBox_for_3")
        self.gridLayout_grading.addWidget(self.spinBox_for_3, 2, 1, 1, 1)
        
        self.label_for_2 = QtWidgets.QLabel(self.groupBox_grading_system)
        self.label_for_2.setObjectName("label_for_2")
        self.gridLayout_grading.addWidget(self.label_for_2, 3, 0, 1, 1)
        
        self.spinBox_for_2 = QtWidgets.QSpinBox(self.groupBox_grading_system)
        self.spinBox_for_2.setMinimum(1)
        self.spinBox_for_2.setMaximum(100)
        self.spinBox_for_2.setProperty("value", 1)
        self.spinBox_for_2.setObjectName("spinBox_for_2")
        self.gridLayout_grading.addWidget(self.spinBox_for_2, 3, 1, 1, 1)
        
        self.verticalLayout_7.addLayout(self.gridLayout_grading)
        
        self.verticalLayout_left.addWidget(self.groupBox_grading_system)
        
        self.horizontalLayout_settings.addLayout(self.verticalLayout_left)
        
        # ПРАВАЯ КОЛОНКА НАСТРОЕК
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        
        self.groupBox_operations = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_operations.setObjectName("groupBox_operations")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_operations)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_addition = QtWidgets.QCheckBox(self.groupBox_operations)
        self.checkBox_addition.setObjectName("checkBox_addition")
        self.verticalLayout_4.addWidget(self.checkBox_addition)
        self.checkBox_subtraction = QtWidgets.QCheckBox(self.groupBox_operations)
        self.checkBox_subtraction.setObjectName("checkBox_subtraction")
        self.verticalLayout_4.addWidget(self.checkBox_subtraction)
        self.checkBox_multiplication = QtWidgets.QCheckBox(self.groupBox_operations)
        self.checkBox_multiplication.setObjectName("checkBox_multiplication")
        self.verticalLayout_4.addWidget(self.checkBox_multiplication)
        self.checkBox_division = QtWidgets.QCheckBox(self.groupBox_operations)
        self.checkBox_division.setObjectName("checkBox_division")
        self.verticalLayout_4.addWidget(self.checkBox_division)
        self.verticalLayout_right.addWidget(self.groupBox_operations)
        
        self.groupBox_settings = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_settings.setObjectName("groupBox_settings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_settings)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox_negatives = QtWidgets.QCheckBox(self.groupBox_settings)
        self.checkBox_negatives.setObjectName("checkBox_negatives")
        self.verticalLayout_5.addWidget(self.checkBox_negatives)
        self.checkBox_fractions = QtWidgets.QCheckBox(self.groupBox_settings)
        self.checkBox_fractions.setObjectName("checkBox_fractions")
        self.verticalLayout_5.addWidget(self.checkBox_fractions)
        self.checkBox_decimals = QtWidgets.QCheckBox(self.groupBox_settings)
        self.checkBox_decimals.setObjectName("checkBox_decimals")
        self.verticalLayout_5.addWidget(self.checkBox_decimals)
        self.checkBox_variables = QtWidgets.QCheckBox(self.groupBox_settings)
        self.checkBox_variables.setObjectName("checkBox_variables")
        self.verticalLayout_5.addWidget(self.checkBox_variables)
        self.verticalLayout_right.addWidget(self.groupBox_settings)
        
        # БЛОК: Настройки диапазона чисел
        self.groupBox_number_range = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_number_range.setObjectName("groupBox_number_range")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_number_range)
        self.gridLayout.setObjectName("gridLayout")
        
        self.label_min = QtWidgets.QLabel(self.groupBox_number_range)
        self.label_min.setObjectName("label_min")
        self.gridLayout.addWidget(self.label_min, 0, 0, 1, 1)
        
        self.spinBox_min = QtWidgets.QSpinBox(self.groupBox_number_range)
        self.spinBox_min.setMinimum(0)  # ИЗМЕНЕНО: минимальное число 0
        self.spinBox_min.setMaximum(999999999)
        self.spinBox_min.setProperty("value", 0)  # ИЗМЕНЕНО: значение по умолчанию 0
        self.spinBox_min.setObjectName("spinBox_min")
        self.gridLayout.addWidget(self.spinBox_min, 0, 1, 1, 1)
        
        self.label_max = QtWidgets.QLabel(self.groupBox_number_range)
        self.label_max.setObjectName("label_max")
        self.gridLayout.addWidget(self.label_max, 1, 0, 1, 1)
        
        self.spinBox_max = QtWidgets.QSpinBox(self.groupBox_number_range)
        self.spinBox_max.setMinimum(0)
        self.spinBox_max.setMaximum(999999999)  # ИЗМЕНЕНО: максимальное число 100000000000
        self.spinBox_max.setProperty("value", 10)
        self.spinBox_max.setObjectName("spinBox_max")
        self.gridLayout.addWidget(self.spinBox_max, 1, 1, 1, 1)
        
        self.verticalLayout_right.addWidget(self.groupBox_number_range)
        
        self.horizontalLayout_settings.addLayout(self.verticalLayout_right)
        
        self.verticalLayout_2.addLayout(self.horizontalLayout_settings)
        
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_set_task_student = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_task_student.setObjectName("pushButton_set_task_student")
        self.horizontalLayout_5.addWidget(self.pushButton_set_task_student)
        self.pushButton_set_task_class = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_task_class.setObjectName("pushButton_set_task_class")
        self.horizontalLayout_5.addWidget(self.pushButton_set_task_class)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_table = QtWidgets.QLabel(self.centralwidget)
        self.label_table.setObjectName("label_table")
        self.verticalLayout_3.addWidget(self.label_table)
        self.tableWidget_grades = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_grades.setObjectName("tableWidget_grades")
        self.tableWidget_grades.setColumnCount(0)
        self.tableWidget_grades.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_grades)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_3.addWidget(self.pushButton_back)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        TeacherViewWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TeacherViewWindow)
        QtCore.QMetaObject.connectSlotsByName(TeacherViewWindow)

    def retranslateUi(self, TeacherViewWindow):
        _translate = QtCore.QCoreApplication.translate
        TeacherViewWindow.setWindowTitle(_translate("TeacherViewWindow", "Просмотр"))
        self.label_title.setText(_translate("TeacherViewWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Просмотр класса и управление учениками</span></p></body></html>"))
        self.label_class.setText(_translate("TeacherViewWindow", "Выберите класс:"))
        self.pushButton_load.setText(_translate("TeacherViewWindow", "Загрузить класс"))
        self.label_students.setText(_translate("TeacherViewWindow", "Ученики класса:"))
        
        # Обновленные подписи для оценок
        self.groupBox_grades.setTitle(_translate("TeacherViewWindow", "Управление оценками"))
        self.label_3.setText(_translate("TeacherViewWindow", "Установка и удаление оценок:"))
        self.label_grade_num.setText(_translate("TeacherViewWindow", "Номер оценки:"))
        self.label_grade_value.setText(_translate("TeacherViewWindow", "Оценка:"))
        self.pushButton_set_grade.setText(_translate("TeacherViewWindow", "Поставить оценку"))
        self.pushButton_delete_grade.setText(_translate("TeacherViewWindow", "Удалить оценку"))
        
        self.label_4.setText(_translate("TeacherViewWindow", "Настройки заданий:"))
        
        # Новая группа: Число действий
        self.groupBox_actions.setTitle(_translate("TeacherViewWindow", "Сложность заданий"))
        self.label_actions.setText(_translate("TeacherViewWindow", "Число действий в примере:"))
        
        # Новая группа: Число переменных
        self.groupBox_variables.setTitle(_translate("TeacherViewWindow", "Переменные"))
        self.label_variables.setText(_translate("TeacherViewWindow", "Число переменных:"))
        
        # Новая группа: Количество примеров
        self.groupBox_examples_count.setTitle(_translate("TeacherViewWindow", "Количество примеров"))
        self.label_examples_count.setText(_translate("TeacherViewWindow", "Количество примеров:"))
        
        # Новая группа: Принцип оценки
        self.groupBox_grading_system.setTitle(_translate("TeacherViewWindow", "Принцип оценки"))
        self.radioButton_standard.setText(_translate("TeacherViewWindow", "Стандартный (80% для 5, 60% для 4, 40% для 3)"))
        self.radioButton_custom.setText(_translate("TeacherViewWindow", "Свои критерии для каждой оценки:"))
        self.label_for_5.setText(_translate("TeacherViewWindow", "Правильных для оценки 5:"))
        self.label_for_4.setText(_translate("TeacherViewWindow", "Правильных для оценки 4:"))
        self.label_for_3.setText(_translate("TeacherViewWindow", "Правильных для оценки 3:"))
        self.label_for_2.setText(_translate("TeacherViewWindow", "Правильных для оценки 2:"))
        
        self.groupBox_operations.setTitle(_translate("TeacherViewWindow", "Операции"))
        self.checkBox_addition.setText(_translate("TeacherViewWindow", "Сложение"))
        self.checkBox_subtraction.setText(_translate("TeacherViewWindow", "Вычитание"))
        self.checkBox_multiplication.setText(_translate("TeacherViewWindow", "Умножение"))
        self.checkBox_division.setText(_translate("TeacherViewWindow", "Деление"))
        self.groupBox_settings.setTitle(_translate("TeacherViewWindow", "Дополнительные настройки"))
        self.checkBox_negatives.setText(_translate("TeacherViewWindow", "Отрицательные числа"))
        self.checkBox_fractions.setText(_translate("TeacherViewWindow", "Дроби"))
        self.checkBox_decimals.setText(_translate("TeacherViewWindow", "Десятичные числа"))
        self.checkBox_variables.setText(_translate("TeacherViewWindow", "Использовать переменные"))
        
        # Надписи для диапазона чисел
        self.groupBox_number_range.setTitle(_translate("TeacherViewWindow", "Диапазон чисел"))
        self.label_min.setText(_translate("TeacherViewWindow", "Минимальное число:"))
        self.label_max.setText(_translate("TeacherViewWindow", "Максимальное число:"))
        
        self.pushButton_set_task_student.setText(_translate("TeacherViewWindow", "Выдать задание ученику"))
        self.pushButton_set_task_class.setText(_translate("TeacherViewWindow", "Выдать задание всему классу"))
        self.label_table.setText(_translate("TeacherViewWindow", "Таблица оценок класса (двойной клик для редактирования):"))
        self.pushButton_back.setText(_translate("TeacherViewWindow", "Назад"))