# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uchitel2_sozd.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Uch_sozd_2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Photo/IMG-20251105-1WA0016.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 641, 2))
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 transparent,\n"
"                                      stop:0.2 #FF5252,\n"
"                                      stop:0.8 #FF5252, \n"
"                                      stop:1 transparent);\n"
"    border: none;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 120, 631, 2))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_2.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 transparent,\n"
"                                      stop:0.2 #FF5252,\n"
"                                      stop:0.8 #FF5252, \n"
"                                      stop:1 transparent);\n"
"    border: none;\n"
"    min-height: 2px;\n"
"    max-height: 2px;\n"
"}")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(290, 60, 2, 341))
        self.line_4.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_4.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 transparent,\n"
"                                      stop:0.2 #FF5252,\n"
"                                      stop:0.8 #FF5252, \n"
"                                      stop:1 transparent);\n"
"    border: none;\n"
"    min-width: 2px;\n"
"    max-width: 2px;\n"
"}")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 90, 160, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setStyleSheet("QRadioButton {\n"
"    color: #1B5E20;\n"
"    font-size: 14px;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 2px solid #00C853;\n"
"    border-radius: 0px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #00E676;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #00E676;\n"
"    border: 2px solid #00C853;\n"
"    border-radius: 8px;\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout.addWidget(self.radioButton)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 32))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 32))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(140, 31))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 31))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(380, 90, 160, 175))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_2.setStyleSheet("QRadioButton {\n"
"    color: #C62828;\n"
"    font-size: 14px;\n"
"    spacing: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 2px solid #FF5252;\n"
"    border-radius: 8px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #FF867C;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #FF5252;\n"
"    border: 2px solid #D32F2F;\n"
"    border-radius: 0px;\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 32))
        self.lineEdit_2.setStyleSheet("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 400, 641, 2))
        self.line_3.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 transparent,\n"
"                                      stop:0.2 #FF5252,\n"
"                                      stop:0.8 #FF5252, \n"
"                                      stop:1 transparent);\n"
"    border: none;\n"
"    min-height: 2px;\n"
"    max-height: 2px;\n"
"}")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 400, 601, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 40, 0)
        self.horizontalLayout.setSpacing(200)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #E74C3C;\n"
"    color: #FFFFFF;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    padding: 8px 15px;\n"
"    min-width: 80px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CB4335;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #A93226;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F5B7B1;\n"
"    color: #7F8C8D;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #00E676;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    color: #1B5E20;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    padding: 2px 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #76FF03;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #00C853;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 350, 231, 41))
        self.label_6.setStyleSheet("color: red")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(360, 290, 191, 16))
        self.label_7.setStyleSheet("color:red")
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "создание"))
        self.label.setText(_translate("MainWindow", "Создание"))
        self.radioButton.setText(_translate("MainWindow", "Ученик"))
        self.label_2.setText(_translate("MainWindow", "Nik ученика "))
        self.label_4.setText(_translate("MainWindow", "Пароль ученика:"))
        self.label_5.setText(_translate("MainWindow", "Класс ученика:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "None"))
        self.radioButton_2.setText(_translate("MainWindow", "Класс"))
        self.label_3.setText(_translate("MainWindow", "Имя класса:"))
        self.pushButton_2.setText(_translate("MainWindow", "ВЫХОД"))
        self.pushButton.setText(_translate("MainWindow", "СОЗДАТЬ"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Внимание: ученик не может иметь оценки </p><p align=\"center\"> пока не будет находиться в классе</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Имя класса не может быть пустым!"))
