# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viber_rezh.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.showFullScreen()
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qconicalgradient(cx: 0.5, cy: 0.5, angle: 45,\n"
"                                 stop: 0 #FFD699, stop: 0.2 #FFCC80,\n"
"                                 stop: 0.4 #FFC266, stop: 0.6 #FFB84D,\n"
"                                 stop: 0.8 #FFAD33, stop: 1 #FFA31A);\n"
"    border: 6px double #FF9800;\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"QWidget#centralwidget {\n"
"    background: rgba(255, 243, 224, 0.85);\n"
"    border: 5px solid #FFB347;\n"
"    border-radius: 25px;\n"
"    margin: 15px;\n"
"}\n"
"\n"
"/* Многослойная граница для окна */\n"
"QMainWindow::separator {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 #FF9800, stop:0.3 #FFB347, \n"
"                                stop:0.7 #FFCC33, stop:1 #FF9800);\n"
"    width: 3px;\n"
"    height: 3px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(820, 200, 246, 66))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: #FFF9F0;\n"
"    border: 3px solid #FFB347;\n"
"    border-radius: 15px;\n"
"    color: #7F4F24;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: normal;\n"
"    padding: 15px 20px;\n"
"    min-width: 200px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #FFF5E6;\n"
"    border: 3px solid #FF9800;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    background-color: #FFF5E6;\n"
"    border: 3px solid #FF9800;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 40px;\n"
"    border-left: 2px solid #FFB347;\n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    background-color: #FFCC33;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 10px solid transparent;\n"
"    border-right: 10px solid transparent;\n"
"    border-top: 10px solid #7F4F24;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFF9F0;\n"
"    border: 3px solid #FFB347;\n"
"    border-radius: 15px;\n"
"    selection-background-color: #FFCC33;\n"
"    color: #7F4F24;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 20px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 10px 15px;\n"
"    border-bottom: 1px solid #FFE0B2;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #FFCC33;\n"
"    color: #7F4F24;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #FFE0B2;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(830, 600, 246, 66))
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    background-color: #FFF9F0;\n"
"    border: 3px solid #FFB347;\n"
"    border-radius: 15px;\n"
"    color: #7F4F24;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: normal;\n"
"    padding: 15px 20px;\n"
"    min-width: 200px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #FFF5E6;\n"
"    border: 3px solid #FF9800;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    background-color: #FFF5E6;\n"
"    border: 3px solid #FF9800;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 40px;\n"
"    border-left: 2px solid #FFB347;\n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    background-color: #FFCC33;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 10px solid transparent;\n"
"    border-right: 10px solid transparent;\n"
"    border-top: 10px solid #7F4F24;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFF9F0;\n"
"    border: 3px solid #FFB347;\n"
"    border-radius: 15px;\n"
"    selection-background-color: #FFCC33;\n"
"    color: #7F4F24;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 20px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 10px 15px;\n"
"    border-bottom: 1px solid #FFE0B2;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #FFCC33;\n"
"    color: #7F4F24;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #FFE0B2;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(760, 480, 491, 81))
        self.label.setStyleSheet("QLabel {\n"
"    color: #7F4F24;  /* Тот же теплый коричневый, что и у кнопки */\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 40px;\n"
"    font-weight: normal;\n"
"    background: transparent;  /* Прозрачный фон */\n"
"    border: none;  /* Без границ */\n"
"    padding: 5px 0px;\n"
"}\n"
"\n"
"QLabel[important=\"true\"] {\n"
"    font-weight: bold;\n"
"    color: #E68900;  /* Более яркий цвет для важных надписей */\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #CC9966;  /* Приглушенный цвет для неактивных надписей */\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(810, 100, 321, 71))
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #7F4F24;  /* Тот же теплый коричневый, что и у кнопки */\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 40px;\n"
"    font-weight: normal;\n"
"    background: transparent;  /* Прозрачный фон */\n"
"    border: none;  /* Без границ */\n"
"    padding: 5px 0px;\n"
"}\n"
"\n"
"QLabel[important=\"true\"] {\n"
"    font-weight: bold;\n"
"    color: #E68900;  /* Более яркий цвет для важных надписей */\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #CC9966;  /* Приглушенный цвет для неактивных надписей */\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(760, 710, 381, 126))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FFB347, stop: 1 #FFCC33);\n"
"    border: 3px solid #FF9800; /* Немного толще граница для баланса */\n"
"    border-radius: 20px; /* Увеличим скругление */\n"
"    color: #7F4F24;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 42px; /* Было 14px, стало 42px */\n"
"    font-weight: bold;\n"
"    padding: 20px 30px; /* Увеличим отступы */\n"
"    min-height: 80px; /* Минимальная высота для удобства */\n"
"    min-width: 200px; /* Минимальная ширина */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FFCC33, stop: 1 #FFB347);\n"
"    border: 3px solid #E68900;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #E68900, stop: 1 #FF9900);\n"
"    padding: 22px 28px 18px 32px; /* Скорректированный эффект нажатия */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1440, 860, 266, 126))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FF6B6B, stop: 1 #FF8E8E);\n"
"    border: 3px solid #FF5252;\n"
"    border-radius: 20px;\n"
"    color: #7C2D2D;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 42px;\n"
"    font-weight: bold;\n"
"    padding: 20px 30px;\n"
"    min-height: 80px;\n"
"    min-width: 200px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FF8E8E, stop: 1 #FF6B6B);\n"
"    border: 3px solid #E04040;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #E04040, stop: 1 #FF5252);\n"
"    padding: 22px 28px 18px 32px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FFCCCC, stop: 1 #FFDDDD);\n"
"    border: 3px solid #FFAAAA;\n"
"    color: #CC8888;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(820, 390, 246, 66))
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    background-color: #FFF9F0;\n"
"    border: 3px solid #FFB347;\n"
"    border-radius: 15px;\n"
"    color: #7F4F24;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 24px;\n"
"    font-weight: normal;\n"
"    padding: 15px 20px;\n"
"    min-width: 200px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #FFF5E6;\n"
"    border: 3px solid #FF9800;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    background-color: #FFF5E6;\n"
"    border: 3px solid #FF9800;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 40px;\n"
"    border-left: 2px solid #FFB347;\n"
"    border-top-right-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    background-color: #FFCC33;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 10px solid transparent;\n"
"    border-right: 10px solid transparent;\n"
"    border-top: 10px solid #7F4F24;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFF9F0;\n"
"    border: 3px solid #FFB347;\n"
"    border-radius: 15px;\n"
"    selection-background-color: #FFCC33;\n"
"    color: #7F4F24;\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 20px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 10px 15px;\n"
"    border-bottom: 1px solid #FFE0B2;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #FFCC33;\n"
"    color: #7F4F24;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #FFE0B2;\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(760, 280, 431, 101))
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #7F4F24;  /* Тот же теплый коричневый, что и у кнопки */\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 40px;\n"
"    font-weight: normal;\n"
"    background: transparent;  /* Прозрачный фон */\n"
"    border: none;  /* Без границ */\n"
"    padding: 5px 0px;\n"
"}\n"
"\n"
"QLabel[important=\"true\"] {\n"
"    font-weight: bold;\n"
"    color: #E68900;  /* Более яркий цвет для важных надписей */\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #CC9966;  /* Приглушенный цвет для неактивных надписей */\n"
"}")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "mathgames"))
        self.comboBox.setItemText(0, _translate("MainWindow", "сложение"))
        self.comboBox.setItemText(1, _translate("MainWindow", "вычитание"))
        self.comboBox.setItemText(2, _translate("MainWindow", "умножение"))
        self.comboBox.setItemText(3, _translate("MainWindow", "деление"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "10"))
        self.label.setText(_translate("MainWindow", "Выбери число примеров:"))
        self.label_2.setText(_translate("MainWindow", "Выбери режим:"))
        self.pushButton.setText(_translate("MainWindow", "НАЧАТЬ"))
        self.pushButton_2.setText(_translate("MainWindow", "ВЫХОД"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "легкий"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "средний"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "сложный"))
        self.label_3.setText(_translate("MainWindow", "Выбери  сложность:"))
